apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
      - name: jenkins-deployment
        image: "jenkins/jenkins:lts"
        ports:
        - containerPort: 80

